# Generated by Django 5.1.2 on 2024-10-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end_date',
            new_name='graduation_date',
        ),
    ]
