# Generated by Django 5.1.2 on 2024-10-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_personalinfo_cep_personalinfo_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
